// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGqL_P6ELM1PzXDCmvkqRdgobXbK6OcSI',
    appId: '1:815561540879:ios:0467c8401d70eabebd2a7a',
    messagingSenderId: '815561540879',
    projectId: 'ftups-ess-monitor-bfe4a',
    storageBucket: 'ftups-ess-monitor-bfe4a.firebasestorage.app',
    iosBundleId: 'com.ftups.ftesshome',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCHSsoSR9BmEh8-3gdcwMszao4wRvjdy8',
    appId: '1:815561540879:web:88b06034b836c52abd2a7a',
    messagingSenderId: '815561540879',
    projectId: 'ftups-ess-monitor-bfe4a',
    authDomain: 'ftups-ess-monitor-bfe4a.firebaseapp.com',
    storageBucket: 'ftups-ess-monitor-bfe4a.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGqL_P6ELM1PzXDCmvkqRdgobXbK6OcSI',
    appId: '1:815561540879:ios:5eb418459506cfa1bd2a7a',
    messagingSenderId: '815561540879',
    projectId: 'ftups-ess-monitor-bfe4a',
    storageBucket: 'ftups-ess-monitor-bfe4a.firebasestorage.app',
    iosBundleId: 'com.example.essMonitorApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1AVPCFmyi5AqaJN-XqHYNxX8Q-ap8dbs',
    appId: '1:815561540879:android:eb0759015db9063dbd2a7a',
    messagingSenderId: '815561540879',
    projectId: 'ftups-ess-monitor-bfe4a',
    storageBucket: 'ftups-ess-monitor-bfe4a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCHSsoSR9BmEh8-3gdcwMszao4wRvjdy8',
    appId: '1:815561540879:web:60514c062c569e4bbd2a7a',
    messagingSenderId: '815561540879',
    projectId: 'ftups-ess-monitor-bfe4a',
    authDomain: 'ftups-ess-monitor-bfe4a.firebaseapp.com',
    storageBucket: 'ftups-ess-monitor-bfe4a.firebasestorage.app',
  );
}
